Repository pfang12/CPSC-2350-Project, pull requests merged in 2024-03, with the labels that each got.

#12 hints and explanation now works, updated the prompt and json format
  App/src/api/gptapi.js
  App/src/components/AttemptingPart.jsx
  App/src/components/Result.jsx
Labels: enhancement

#14 11-replace-ilovepdf
  App/package-lock.json
  App/package.json
  App/src/api/pdfHandler.js
  App/src/api/pdfapi.js
  App/src/components/InputComponent.jsx
  package-lock.json
  package.json
Labels: bug, enhancement, urgent

#21 Feedback functions
  App/src/api/gptapi.js
  App/src/components/InputComponent.jsx
Labels: enhancement

#24 Site redesign
  App/package-lock.json
  App/package.json
  App/src/components/AttemptingPart.jsx
  App/src/components/Divider.jsx
  App/src/components/InputComponent.jsx
  App/src/components/LoadingSpinner.jsx
  App/src/components/Navbar.jsx
  App/src/components/QuizComponent.jsx
  App/src/components/Result.jsx
  App/src/index.css
  App/src/pages/Home.jsx
  App/tailwind.config.js
Labels: enhancement

#26 Fix gpt function names
  App/index.html
  App/public/favicon.ico
  App/src/components/InputComponent.jsx
Labels: bug

#29 Answers and Password options
  App/public/templates/quiz-mcq-na-template.docx
  App/public/templates/quiz-mcq-wa-template.docx
  App/public/templates/quiz-tf-na-template.docx
  App/public/templates/quiz-tf-wa-template.docx
  App/public/templates/quiz-wa-template.docx
  App/public/templates/quiz-wa.docx
  App/src/api/pdfapi.js
  App/src/components/InputComponent.jsx
Labels: enhancement, development
